// This file is auto-generated by @hey-api/openapi-ts

export const ZipCodeDtoSchema = {
    type: 'object',
    properties: {
        street: {
            type: 'string',
            default: 'Example Street'
        },
        city: {
            type: 'string',
            default: 'Amsterdam'
        },
        country: {
            type: 'string',
            default: 'Nederland'
        }
    },
    required: ['street', 'city', 'country']
} as const;

export const CreateUserDtoSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            default: 'John'
        },
        lastName: {
            type: 'string',
            default: 'Doe'
        },
        id: {
            type: 'string',
            default: 'abcdefghijklmnopqrstuvwxyzaa'
        },
        email: {
            type: 'string',
            default: 'user@example.com'
        }
    },
    required: ['firstName', 'lastName', 'id', 'email']
} as const;

export const UserDtoSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            default: 'John'
        },
        lastName: {
            type: 'string',
            default: 'Doe'
        },
        id: {
            type: 'string',
            default: 'abcdefghijklmnopqrstuvwxyzaa'
        },
        email: {
            type: 'string',
            default: 'user@example.com'
        }
    },
    required: ['firstName', 'lastName', 'id', 'email']
} as const;

export const UpdateUserDtoSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            default: 'John'
        },
        lastName: {
            type: 'string',
            default: 'Doe'
        },
        email: {
            type: 'string',
            default: 'user@example.com'
        }
    },
    required: ['firstName', 'lastName', 'email']
} as const;

export const CompanyDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            default: 0
        },
        companyEmail: {
            type: 'string',
            default: 'admin@example.com'
        },
        companyName: {
            type: 'string',
            default: 'example.com'
        },
        companyNumber: {
            type: 'string',
            default: '93056589',
            nullable: true
        },
        taxNumber: {
            type: 'string',
            default: 'NL123456789B01',
            nullable: true
        },
        streetName: {
            type: 'string',
            default: 'Example Street'
        },
        houseNumber: {
            type: 'string',
            default: '11'
        },
        addition: {
            type: 'string',
            default: 'E',
            nullable: true
        },
        zipCode: {
            type: 'string',
            default: '1234AB'
        },
        city: {
            type: 'string',
            default: 'Amsterdam'
        },
        country: {
            type: 'string',
            default: 'The Netherlands'
        }
    },
    required: ['id', 'companyEmail', 'companyName', 'companyNumber', 'taxNumber', 'streetName', 'houseNumber', 'addition', 'zipCode', 'city', 'country']
} as const;

export const ProfileDtoSchema = {
    type: 'object',
    properties: {
        user: {
            allOf: [
                {
                    '$ref': '#/components/schemas/UserDto'
                }
            ]
        },
        company: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CompanyDto'
                }
            ]
        }
    },
    required: ['user', 'company']
} as const;

export const CreateCompanyDtoSchema = {
    type: 'object',
    properties: {
        companyEmail: {
            type: 'string',
            default: 'admin@example.com'
        },
        companyName: {
            type: 'string',
            default: 'example.com'
        },
        companyNumber: {
            type: 'string',
            default: '93056589',
            nullable: true
        },
        taxNumber: {
            type: 'string',
            default: 'NL123456789B01',
            nullable: true
        },
        streetName: {
            type: 'string',
            default: 'Example Street'
        },
        houseNumber: {
            type: 'string',
            default: '11'
        },
        addition: {
            type: 'string',
            default: 'E',
            nullable: true
        },
        zipCode: {
            type: 'string',
            default: '1234AB'
        },
        city: {
            type: 'string',
            default: 'Amsterdam'
        },
        country: {
            type: 'string',
            default: 'The Netherlands'
        }
    },
    required: ['companyEmail', 'companyName', 'companyNumber', 'taxNumber', 'streetName', 'houseNumber', 'addition', 'zipCode', 'city', 'country']
} as const;

export const UpdateCompanyDtoSchema = {
    type: 'object',
    properties: {
        companyEmail: {
            type: 'string',
            default: 'admin@example.com'
        },
        companyName: {
            type: 'string',
            default: 'example.com'
        },
        companyNumber: {
            type: 'string',
            default: '93056589',
            nullable: true
        },
        taxNumber: {
            type: 'string',
            default: 'NL123456789B01',
            nullable: true
        },
        streetName: {
            type: 'string',
            default: 'Example Street'
        },
        houseNumber: {
            type: 'string',
            default: '11'
        },
        addition: {
            type: 'string',
            default: 'E',
            nullable: true
        },
        zipCode: {
            type: 'string',
            default: '1234AB'
        },
        city: {
            type: 'string',
            default: 'Amsterdam'
        },
        country: {
            type: 'string',
            default: 'The Netherlands'
        }
    },
    required: ['companyEmail', 'companyName', 'companyNumber', 'taxNumber', 'streetName', 'houseNumber', 'addition', 'zipCode', 'city', 'country']
} as const;

export const CompanyUserDtoSchema = {
    type: 'object',
    properties: {
        companyId: {
            type: 'number',
            default: 0
        },
        userId: {
            type: 'string',
            default: 'abcdefghijklmnopqrstuvwxyzaa'
        },
        user: {
            allOf: [
                {
                    '$ref': '#/components/schemas/UserDto'
                }
            ]
        }
    },
    required: ['companyId', 'userId', 'user']
} as const;

export const CreateCompanyUserDtoSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            default: 'abcdefghijklmnopqrstuvwxyzaa'
        }
    },
    required: ['userId']
} as const;

export const PaymentDetailsDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            default: 0
        },
        iban: {
            type: 'string',
            default: 'GB82WEST12345698765432'
        },
        currency: {
            type: 'string',
            default: 'EUR',
            enum: ['EUR', 'USD', 'GBP']
        }
    },
    required: ['id', 'iban', 'currency']
} as const;

export const CreatePaymentDetailsDtoSchema = {
    type: 'object',
    properties: {
        iban: {
            type: 'string',
            default: 'GB82WEST12345698765432'
        },
        currency: {
            type: 'string',
            default: 'EUR',
            enum: ['EUR', 'USD', 'GBP']
        }
    },
    required: ['iban', 'currency']
} as const;

export const UpdatePaymentDetailsDtoSchema = {
    type: 'object',
    properties: {
        iban: {
            type: 'string',
            default: 'GB82WEST12345698765432'
        },
        currency: {
            type: 'string',
            default: 'EUR',
            enum: ['EUR', 'USD', 'GBP']
        }
    },
    required: ['iban', 'currency']
} as const;

export const InvoiceCompanyDetailsDtoSchema = {
    type: 'object',
    properties: {
        streetName: {
            type: 'string',
            default: 'Example Street'
        },
        houseNumber: {
            type: 'string',
            default: '11'
        },
        addition: {
            type: 'string',
            default: 'E',
            nullable: true
        },
        zipCode: {
            type: 'string',
            default: '1234AB'
        },
        city: {
            type: 'string',
            default: 'Amsterdam'
        },
        country: {
            type: 'string',
            default: 'The Netherlands'
        },
        companyEmail: {
            type: 'string',
            default: 'admin@example.com'
        },
        companyName: {
            type: 'string',
            default: 'example.com'
        },
        companyNumber: {
            type: 'string',
            default: '93056589',
            nullable: true
        },
        taxNumber: {
            type: 'string',
            default: 'NL123456789B01',
            nullable: true
        }
    },
    required: ['streetName', 'houseNumber', 'addition', 'zipCode', 'city', 'country', 'companyEmail', 'companyName', 'companyNumber', 'taxNumber']
} as const;

export const InvoiceAddresseeDetailsDtoSchema = {
    type: 'object',
    properties: {
        streetName: {
            type: 'string',
            default: 'Example Street'
        },
        houseNumber: {
            type: 'string',
            default: '11'
        },
        addition: {
            type: 'string',
            default: 'E',
            nullable: true
        },
        zipCode: {
            type: 'string',
            default: '1234AB'
        },
        city: {
            type: 'string',
            default: 'Amsterdam'
        },
        country: {
            type: 'string',
            default: 'The Netherlands'
        },
        companyName: {
            type: 'string',
            default: 'example.com'
        },
        attention: {
            type: 'string',
            default: null,
            nullable: true
        },
        subject: {
            type: 'string',
            default: null,
            nullable: true
        }
    },
    required: ['streetName', 'houseNumber', 'addition', 'zipCode', 'city', 'country', 'companyName', 'attention', 'subject']
} as const;

export const InvoiceProductDtoSchema = {
    type: 'object',
    properties: {
        description: {
            type: 'string',
            default: 'Example Product'
        },
        amount: {
            type: 'number',
            default: 1
        },
        tariff: {
            type: 'number',
            default: 19.95
        },
        taxRate: {
            type: 'number',
            default: 21
        },
        cost: {
            type: 'number',
            default: 19.95
        }
    },
    required: ['description', 'amount', 'tariff', 'taxRate', 'cost']
} as const;

export const InvoicePriceDtoSchema = {
    type: 'object',
    properties: {
        subtotal: {
            type: 'number',
            default: 19.95
        },
        taxAmount: {
            type: 'number',
            default: 4.19
        },
        total: {
            type: 'number',
            default: 24.14
        }
    },
    required: ['subtotal', 'taxAmount', 'total']
} as const;

export const InvoicePaymentDetailsDtoSchema = {
    type: 'object',
    properties: {
        iban: {
            type: 'string',
            default: 'GB82WEST12345698765432'
        },
        currency: {
            type: 'string',
            default: 'EUR',
            enum: ['EUR', 'USD', 'GBP']
        },
        invoiceDate: {
            type: 'string',
            default: '2024-11-17T13:51:23.867Z',
            format: 'date-time'
        },
        dueDate: {
            type: 'string',
            default: '2024-11-17T13:51:23.868Z',
            format: 'date-time'
        },
        invoiceNumber: {
            type: 'string',
            default: '00000'
        }
    },
    required: ['iban', 'currency', 'invoiceDate', 'dueDate', 'invoiceNumber']
} as const;

export const InvoiceDtoSchema = {
    type: 'object',
    properties: {
        companyDetails: {
            '$ref': '#/components/schemas/InvoiceCompanyDetailsDto'
        },
        addresseeDetails: {
            '$ref': '#/components/schemas/InvoiceAddresseeDetailsDto'
        },
        products: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/InvoiceProductDto'
            }
        },
        price: {
            '$ref': '#/components/schemas/InvoicePriceDto'
        },
        paymentDetails: {
            '$ref': '#/components/schemas/InvoicePaymentDetailsDto'
        },
        language: {
            type: 'string',
            default: 'en_GB',
            enum: ['nl-NL', 'en-US', 'en-GB']
        }
    },
    required: ['companyDetails', 'addresseeDetails', 'products', 'price', 'paymentDetails', 'language']
} as const;