// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { AppControllerGetHelloError, AppControllerGetHelloResponse, GetZipCodeData, GetZipCodeError, GetZipCodeResponse, GetBoldFontError, GetBoldFontResponse, GetRegularFontError, GetRegularFontResponse, CreateUserData, CreateUserError, CreateUserResponse, DeleteCurrentUserError, DeleteCurrentUserResponse, UpdateCurrentUserData, UpdateCurrentUserError, UpdateCurrentUserResponse, GetCurrentUserError, GetCurrentUserResponse, GetCurrentUserProfileError, GetCurrentUserProfileResponse, GetUserExistsByEmailData, GetUserExistsByEmailError, GetUserExistsByEmailResponse, CreateCompanyData, CreateCompanyError, CreateCompanyResponse, GetCurrentCompanyError, GetCurrentCompanyResponse, UpdateCurrentCompanyData, UpdateCurrentCompanyError, UpdateCurrentCompanyResponse, GetCurrentCompanyUsersError, GetCurrentCompanyUsersResponse, CreateCurrentCompanyUserData, CreateCurrentCompanyUserError, CreateCurrentCompanyUserResponse, DeleteCurrentCompanyUserData, DeleteCurrentCompanyUserError, DeleteCurrentCompanyUserResponse, GetCurrentCompanyPaymentDetailsError, GetCurrentCompanyPaymentDetailsResponse, CreateCurrentCompanyPaymentDetailsData, CreateCurrentCompanyPaymentDetailsError, CreateCurrentCompanyPaymentDetailsResponse, UpdateCurrentCompanyPaymentDetailsData, UpdateCurrentCompanyPaymentDetailsError, UpdateCurrentCompanyPaymentDetailsResponse, CreateInvoiceData, CreateInvoiceError, CreateInvoiceResponse } from './types.gen';

export const client = createClient(createConfig());

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<AppControllerGetHelloResponse, AppControllerGetHelloError, ThrowOnError>({
        ...options,
        url: '/'
    });
};

export const getZipCode = <ThrowOnError extends boolean = false>(options: Options<GetZipCodeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetZipCodeResponse, GetZipCodeError, ThrowOnError>({
        ...options,
        url: '/zip-code'
    });
};

export const getBoldFont = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetBoldFontResponse, GetBoldFontError, ThrowOnError>({
        ...options,
        url: '/fonts/bold'
    });
};

export const getRegularFont = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRegularFontResponse, GetRegularFontError, ThrowOnError>({
        ...options,
        url: '/fonts/regular'
    });
};

export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateUserResponse, CreateUserError, ThrowOnError>({
        ...options,
        url: '/users'
    });
};

export const deleteCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteCurrentUserResponse, DeleteCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

export const updateCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentUserData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateCurrentUserResponse, UpdateCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentUserResponse, GetCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

export const getCurrentUserProfile = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentUserProfileResponse, GetCurrentUserProfileError, ThrowOnError>({
        ...options,
        url: '/users/me/profile'
    });
};

export const getUserExistsByEmail = <ThrowOnError extends boolean = false>(options: Options<GetUserExistsByEmailData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserExistsByEmailResponse, GetUserExistsByEmailError, ThrowOnError>({
        ...options,
        url: '/users/{email}/exists'
    });
};

export const createCompany = <ThrowOnError extends boolean = false>(options: Options<CreateCompanyData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateCompanyResponse, CreateCompanyError, ThrowOnError>({
        ...options,
        url: '/companies'
    });
};

export const getCurrentCompany = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentCompanyResponse, GetCurrentCompanyError, ThrowOnError>({
        ...options,
        url: '/companies/my'
    });
};

export const updateCurrentCompany = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentCompanyData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateCurrentCompanyResponse, UpdateCurrentCompanyError, ThrowOnError>({
        ...options,
        url: '/companies/my'
    });
};

export const getCurrentCompanyUsers = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentCompanyUsersResponse, GetCurrentCompanyUsersError, ThrowOnError>({
        ...options,
        url: '/companies/my/users'
    });
};

export const createCurrentCompanyUser = <ThrowOnError extends boolean = false>(options: Options<CreateCurrentCompanyUserData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateCurrentCompanyUserResponse, CreateCurrentCompanyUserError, ThrowOnError>({
        ...options,
        url: '/companies/my/users'
    });
};

export const deleteCurrentCompanyUser = <ThrowOnError extends boolean = false>(options: Options<DeleteCurrentCompanyUserData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteCurrentCompanyUserResponse, DeleteCurrentCompanyUserError, ThrowOnError>({
        ...options,
        url: '/companies/my/users/{userId}'
    });
};

export const getCurrentCompanyPaymentDetails = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentCompanyPaymentDetailsResponse, GetCurrentCompanyPaymentDetailsError, ThrowOnError>({
        ...options,
        url: '/companies/my/payment-details'
    });
};

export const createCurrentCompanyPaymentDetails = <ThrowOnError extends boolean = false>(options: Options<CreateCurrentCompanyPaymentDetailsData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateCurrentCompanyPaymentDetailsResponse, CreateCurrentCompanyPaymentDetailsError, ThrowOnError>({
        ...options,
        url: '/companies/my/payment-details'
    });
};

export const updateCurrentCompanyPaymentDetails = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentCompanyPaymentDetailsData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateCurrentCompanyPaymentDetailsResponse, UpdateCurrentCompanyPaymentDetailsError, ThrowOnError>({
        ...options,
        url: '/companies/my/payment-details'
    });
};

export const createInvoice = <ThrowOnError extends boolean = false>(options: Options<CreateInvoiceData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateInvoiceResponse, CreateInvoiceError, ThrowOnError>({
        ...options,
        url: '/invoice'
    });
};