// This file is auto-generated by @hey-api/openapi-ts

export type ZipCodeDto = {
    street: string;
    city: string;
    country: string;
};

export type CreateUserDto = {
    firstName: string;
    lastName: string;
    id: string;
    email: string;
};

export type UserDto = {
    firstName: string;
    lastName: string;
    id: string;
    email: string;
};

export type UpdateUserDto = {
    firstName: string;
    lastName: string;
    email: string;
};

export type CompanyDto = {
    id: number;
    companyEmail: string;
    companyName: string;
    companyNumber?: string;
    taxNumber?: string;
    streetName: string;
    houseNumber: string;
    addition?: string;
    zipCode: string;
    city: string;
    country: string;
};

export type ProfileDto = {
    user: UserDto;
    company: CompanyDto;
};

export type CreateCompanyDto = {
    companyEmail: string;
    companyName: string;
    companyNumber?: string;
    taxNumber?: string;
    streetName: string;
    houseNumber: string;
    addition?: string;
    zipCode: string;
    city: string;
    country: string;
};

export type UpdateCompanyDto = {
    companyEmail: string;
    companyName: string;
    companyNumber?: string;
    taxNumber?: string;
    streetName: string;
    houseNumber: string;
    addition?: string;
    zipCode: string;
    city: string;
    country: string;
};

export type CompanyUserDto = {
    companyId: number;
    userId: string;
    user: UserDto;
};

export type CreateCompanyUserDto = {
    userId: string;
};

export type PaymentDetailsDto = {
    id: number;
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
};

export enum currency {
    EUR = 'EUR',
    USD = 'USD',
    GBP = 'GBP'
}

export type CreatePaymentDetailsDto = {
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
};

export type UpdatePaymentDetailsDto = {
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
};

export type AppControllerGetHelloResponse = unknown;

export type AppControllerGetHelloError = unknown;

export type GetZipCodeData = {
    query: {
        houseNumber: string;
        zipCode: string;
    };
};

export type GetZipCodeResponse = ZipCodeDto;

export type GetZipCodeError = unknown;

export type GetBoldFontResponse = unknown;

export type GetBoldFontError = unknown;

export type GetRegularFontResponse = unknown;

export type GetRegularFontError = unknown;

export type CreateUserData = {
    body: CreateUserDto;
};

export type CreateUserResponse = UserDto;

export type CreateUserError = unknown;

export type DeleteCurrentUserResponse = UserDto;

export type DeleteCurrentUserError = unknown;

export type UpdateCurrentUserData = {
    body: UpdateUserDto;
};

export type UpdateCurrentUserResponse = UserDto;

export type UpdateCurrentUserError = unknown;

export type GetCurrentUserResponse = UserDto;

export type GetCurrentUserError = unknown;

export type GetCurrentUserProfileResponse = ProfileDto;

export type GetCurrentUserProfileError = unknown;

export type CreateCompanyData = {
    body: CreateCompanyDto;
};

export type CreateCompanyResponse = CompanyDto;

export type CreateCompanyError = unknown;

export type GetCurrentCompanyResponse = CompanyDto;

export type GetCurrentCompanyError = unknown;

export type UpdateCurrentCompanyData = {
    body: UpdateCompanyDto;
};

export type UpdateCurrentCompanyResponse = CompanyDto;

export type UpdateCurrentCompanyError = unknown;

export type GetCurrentCompanyUsersResponse = Array<CompanyUserDto>;

export type GetCurrentCompanyUsersError = unknown;

export type CreateCurrentCompanyUserData = {
    body: CreateCompanyUserDto;
};

export type CreateCurrentCompanyUserResponse = CompanyUserDto;

export type CreateCurrentCompanyUserError = unknown;

export type DeleteCurrentCompanyUserData = {
    path: {
        userId: string;
    };
};

export type DeleteCurrentCompanyUserResponse = CompanyUserDto;

export type DeleteCurrentCompanyUserError = unknown;

export type GetCurrentCompanyPaymentDetailsResponse = PaymentDetailsDto;

export type GetCurrentCompanyPaymentDetailsError = unknown;

export type CreateCurrentCompanyPaymentDetailsData = {
    body: CreatePaymentDetailsDto;
};

export type CreateCurrentCompanyPaymentDetailsResponse = PaymentDetailsDto;

export type CreateCurrentCompanyPaymentDetailsError = unknown;

export type UpdateCurrentCompanyPaymentDetailsData = {
    body: UpdatePaymentDetailsDto;
};

export type UpdateCurrentCompanyPaymentDetailsResponse = PaymentDetailsDto;

export type UpdateCurrentCompanyPaymentDetailsError = unknown;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                '200': unknown;
            };
        };
    };
    '/zip-code': {
        get: {
            req: GetZipCodeData;
            res: {
                '200': ZipCodeDto;
            };
        };
    };
    '/fonts/bold': {
        get: {
            res: {
                '200': unknown;
            };
        };
    };
    '/fonts/regular': {
        get: {
            res: {
                '200': unknown;
            };
        };
    };
    '/users': {
        post: {
            req: CreateUserData;
            res: {
                '200': UserDto;
            };
        };
    };
    '/users/me': {
        delete: {
            res: {
                '200': UserDto;
            };
        };
        put: {
            req: UpdateCurrentUserData;
            res: {
                '200': UserDto;
            };
        };
        get: {
            res: {
                '200': UserDto;
            };
        };
    };
    '/users/me/profile': {
        get: {
            res: {
                '200': ProfileDto;
            };
        };
    };
    '/companies': {
        post: {
            req: CreateCompanyData;
            res: {
                '200': CompanyDto;
            };
        };
    };
    '/companies/my': {
        get: {
            res: {
                '200': CompanyDto;
            };
        };
        put: {
            req: UpdateCurrentCompanyData;
            res: {
                '200': CompanyDto;
            };
        };
    };
    '/companies/my/users': {
        get: {
            res: {
                '200': Array<CompanyUserDto>;
            };
        };
        post: {
            req: CreateCurrentCompanyUserData;
            res: {
                '200': CompanyUserDto;
            };
        };
    };
    '/companies/my/users/{userId}': {
        delete: {
            req: DeleteCurrentCompanyUserData;
            res: {
                '200': CompanyUserDto;
            };
        };
    };
    '/companies/my/payment-details': {
        get: {
            res: {
                '200': PaymentDetailsDto;
            };
        };
        post: {
            req: CreateCurrentCompanyPaymentDetailsData;
            res: {
                '200': PaymentDetailsDto;
            };
        };
        put: {
            req: UpdateCurrentCompanyPaymentDetailsData;
            res: {
                '200': PaymentDetailsDto;
            };
        };
    };
};