// This file is auto-generated by @hey-api/openapi-ts

export type CompanyDto = {
    id: number;
    companyEmail: string;
    companyName: string;
    companyNumber: (string) | null;
    taxNumber: (string) | null;
    streetName: string;
    houseNumber: string;
    addition: (string) | null;
    zipCode: string;
    city: string;
    country: string;
};

export type CompanyUserDto = {
    companyId: number;
    userId: string;
    user: (UserDto);
};

export type CreateCompanyDto = {
    companyEmail: string;
    companyName: string;
    companyNumber: (string) | null;
    taxNumber: (string) | null;
    streetName: string;
    houseNumber: string;
    addition: (string) | null;
    zipCode: string;
    city: string;
    country: string;
};

export type CreateCompanyUserDto = {
    userId: string;
};

export type CreatePaymentDetailsDto = {
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
};

export enum currency {
    EUR = 'EUR',
    USD = 'USD',
    GBP = 'GBP'
}

export type CreateUserDto = {
    firstName: string;
    lastName: string;
    id: string;
    email: string;
};

export type InvoiceAddresseeDetailsDto = {
    streetName: string;
    houseNumber: string;
    addition: (string) | null;
    zipCode: string;
    city: string;
    country: string;
    companyName: string;
    attention: (string) | null;
    subject: (string) | null;
};

export type InvoiceCompanyDetailsDto = {
    streetName: string;
    houseNumber: string;
    addition: (string) | null;
    zipCode: string;
    city: string;
    country: string;
    companyEmail: string;
    companyName: string;
    companyNumber: (string) | null;
    taxNumber: (string) | null;
};

export type InvoiceDto = {
    companyDetails: InvoiceCompanyDetailsDto;
    addresseeDetails: InvoiceAddresseeDetailsDto;
    products: Array<InvoiceProductDto>;
    price: InvoicePriceDto;
    paymentDetails: InvoicePaymentDetailsDto;
    language: 'nl-NL' | 'en-US' | 'en-GB';
};

export enum language {
    NL_NL = 'nl-NL',
    EN_US = 'en-US',
    EN_GB = 'en-GB'
}

export type InvoicePaymentDetailsDto = {
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
    invoiceDate: Date;
    dueDate: Date;
    invoiceNumber: string;
};

export type InvoicePriceDto = {
    subtotal: number;
    taxAmount: number;
    total: number;
};

export type InvoiceProductDto = {
    description: string;
    amount: number;
    tariff: number;
    taxRate: number;
    cost: number;
};

export type PaymentDetailsDto = {
    id: number;
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
};

export type ProfileDto = {
    user: (UserDto);
    company: (CompanyDto);
};

export type UpdateCompanyDto = {
    companyEmail: string;
    companyName: string;
    companyNumber: (string) | null;
    taxNumber: (string) | null;
    streetName: string;
    houseNumber: string;
    addition: (string) | null;
    zipCode: string;
    city: string;
    country: string;
};

export type UpdatePaymentDetailsDto = {
    iban: string;
    currency: 'EUR' | 'USD' | 'GBP';
};

export type UpdateUserDto = {
    firstName: string;
    lastName: string;
    email: string;
};

export type UserDto = {
    firstName: string;
    lastName: string;
    id: string;
    email: string;
};

export type ZipCodeDto = {
    street: string;
    city: string;
    country: string;
};

export type AppControllerGetHelloResponse = (unknown);

export type AppControllerGetHelloError = unknown;

export type GetZipCodeData = {
    query: {
        houseNumber: string;
        zipCode: string;
    };
};

export type GetZipCodeResponse = (ZipCodeDto);

export type GetZipCodeError = unknown;

export type GetBoldFontResponse = (unknown);

export type GetBoldFontError = unknown;

export type GetRegularFontResponse = (unknown);

export type GetRegularFontError = unknown;

export type CreateUserData = {
    body: CreateUserDto;
};

export type CreateUserResponse = (UserDto);

export type CreateUserError = unknown;

export type DeleteCurrentUserResponse = (UserDto);

export type DeleteCurrentUserError = unknown;

export type UpdateCurrentUserData = {
    body: UpdateUserDto;
};

export type UpdateCurrentUserResponse = (UserDto);

export type UpdateCurrentUserError = unknown;

export type GetCurrentUserResponse = (UserDto);

export type GetCurrentUserError = unknown;

export type GetCurrentUserProfileResponse = (ProfileDto);

export type GetCurrentUserProfileError = unknown;

export type GetUserExistsByEmailData = {
    path: {
        email: string;
    };
};

export type GetUserExistsByEmailResponse = (boolean);

export type GetUserExistsByEmailError = unknown;

export type CreateCompanyData = {
    body: CreateCompanyDto;
};

export type CreateCompanyResponse = (CompanyDto);

export type CreateCompanyError = unknown;

export type GetCurrentCompanyResponse = (CompanyDto);

export type GetCurrentCompanyError = unknown;

export type UpdateCurrentCompanyData = {
    body: UpdateCompanyDto;
};

export type UpdateCurrentCompanyResponse = (CompanyDto);

export type UpdateCurrentCompanyError = unknown;

export type GetCurrentCompanyUsersResponse = (Array<CompanyUserDto>);

export type GetCurrentCompanyUsersError = unknown;

export type CreateCurrentCompanyUserData = {
    body: CreateCompanyUserDto;
};

export type CreateCurrentCompanyUserResponse = (CompanyUserDto);

export type CreateCurrentCompanyUserError = unknown;

export type DeleteCurrentCompanyUserData = {
    path: {
        userId: string;
    };
};

export type DeleteCurrentCompanyUserResponse = (CompanyUserDto);

export type DeleteCurrentCompanyUserError = unknown;

export type GetCurrentCompanyPaymentDetailsResponse = (PaymentDetailsDto);

export type GetCurrentCompanyPaymentDetailsError = unknown;

export type CreateCurrentCompanyPaymentDetailsData = {
    body: CreatePaymentDetailsDto;
};

export type CreateCurrentCompanyPaymentDetailsResponse = (PaymentDetailsDto);

export type CreateCurrentCompanyPaymentDetailsError = unknown;

export type UpdateCurrentCompanyPaymentDetailsData = {
    body: UpdatePaymentDetailsDto;
};

export type UpdateCurrentCompanyPaymentDetailsResponse = (PaymentDetailsDto);

export type UpdateCurrentCompanyPaymentDetailsError = unknown;

export type CreateInvoiceData = {
    body: InvoiceDto;
};

export type CreateInvoiceResponse = (unknown);

export type CreateInvoiceError = unknown;