name: E2E Test

on: [workflow_call]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm run dev
          browser: chrome
          headed: true
